### ISSUE TITLE
Failure with dev scales

### ISSUE THREAD

**Issue by hadley** [jhrcook/ggasym#21]
The development version of scales now uses farver to perform colour interpolation. This has result in a few non-perceptual changes to changes, and it looks like you're testing for exact equality:

```
 Failure: scale_fill_tl/br/diag_gradient2 values populate properly (@test-scale_continuous_asym.R#185)
  g3_build$data[[3]]$fill_diag not equal to `diag_cols`.
  2/6 mismatches
  x[1]: "#E40081"
  y[1]: "#E30081"
  
  x[3]: "#E40081"
  y[3]: "#E30081"
```

Would you mind relaxing the test so I can get scales to CRAN in the next week or so?

**Comment by jhrcook** [comment]
Can I use the dev version of scales to update the expected values? The test as it is written is useful because it means the cells are being populated with the correct colors.

**Comment by hadley** [comment]
You could, but you'll need to condition of the version of scales installed so that your package passes R CMD check with either version installed.

**Comment by jhrcook** [comment]
I have fixed the tests to adjust for the version of 'scales' the user has installed. Thank you for opening this issue before releasing the newest version of 'scales'.

I have submitted 'ggasym' 0.1.2 to CRAN.

**Comment by hadley** [comment]
Thanks!
